/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as GetInvolvedRouteImport } from './routes/get-involved'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MediaIndexRouteImport } from './routes/media.index'
import { Route as MediaSlugRouteImport } from './routes/media.$slug'

const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const GetInvolvedRoute = GetInvolvedRouteImport.update({
  id: '/get-involved',
  path: '/get-involved',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaIndexRoute = MediaIndexRouteImport.update({
  id: '/media/',
  path: '/media/',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaSlugRoute = MediaSlugRouteImport.update({
  id: '/media/$slug',
  path: '/media/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/gallery': typeof GalleryRoute
  '/get-involved': typeof GetInvolvedRoute
  '/programs': typeof ProgramsRoute
  '/media/$slug': typeof MediaSlugRoute
  '/media/': typeof MediaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/gallery': typeof GalleryRoute
  '/get-involved': typeof GetInvolvedRoute
  '/programs': typeof ProgramsRoute
  '/media/$slug': typeof MediaSlugRoute
  '/media': typeof MediaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/gallery': typeof GalleryRoute
  '/get-involved': typeof GetInvolvedRoute
  '/programs': typeof ProgramsRoute
  '/media/$slug': typeof MediaSlugRoute
  '/media/': typeof MediaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/donate'
    | '/gallery'
    | '/get-involved'
    | '/programs'
    | '/media/$slug'
    | '/media/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/donate'
    | '/gallery'
    | '/get-involved'
    | '/programs'
    | '/media/$slug'
    | '/media'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/donate'
    | '/gallery'
    | '/get-involved'
    | '/programs'
    | '/media/$slug'
    | '/media/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DonateRoute: typeof DonateRoute
  GalleryRoute: typeof GalleryRoute
  GetInvolvedRoute: typeof GetInvolvedRoute
  ProgramsRoute: typeof ProgramsRoute
  MediaSlugRoute: typeof MediaSlugRoute
  MediaIndexRoute: typeof MediaIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-involved': {
      id: '/get-involved'
      path: '/get-involved'
      fullPath: '/get-involved'
      preLoaderRoute: typeof GetInvolvedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media/': {
      id: '/media/'
      path: '/media'
      fullPath: '/media/'
      preLoaderRoute: typeof MediaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media/$slug': {
      id: '/media/$slug'
      path: '/media/$slug'
      fullPath: '/media/$slug'
      preLoaderRoute: typeof MediaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DonateRoute: DonateRoute,
  GalleryRoute: GalleryRoute,
  GetInvolvedRoute: GetInvolvedRoute,
  ProgramsRoute: ProgramsRoute,
  MediaSlugRoute: MediaSlugRoute,
  MediaIndexRoute: MediaIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
